theme = "dracula"

[editor]
line-number = "relative"
bufferline = "multiple"
color-modes = true
popup-border = "all"

[editor.statusline]
left = ["mode", "spinner", "diagnostics"]
center = ["file-name", "read-only-indicator", "file-modification-indicator"]
right = [
  "selections",
  "register",
  "position",
  "position-percentage",
  "file-encoding",
  "file-type",
]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·"  # Tabs will look like "→···" (depending on tab width)

[editor.soft-wrap]
enable = true

[editor.lsp]
display-inlay-hints = true

# [keys.normal]
# ";" = "command_mode"

# [keys.insert]
# j = { k = "normal_mode" }
