theme = "zed_onedark"

[editor]
line-number = "relative"
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.lsp]
display-inlay-hints = true

[keys.normal]
";" = "command_mode"

[keys.insert]
j = { k = "normal_mode" }
